title: Jaewoo Kim
logo: /assets/img/logo.jpg
email: <a href="mailto:"jw.kim@kaist.ac.kr">jw.kim@kaist.ac.kr</a>
description: 
show_downloads: false
google_analytics: G-GV2C824418
color-scheme: light
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

sidebar:
  - name: Curriculum Vitae
    icon: <i class="fas fa-file-alt"></i>
    link: /sources/CV_JaewooKim (2024-05-29).pdf
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/jaewoo-space

github: [metadata]
